### ISSUE TITLE
Migrate non-Spark physionet LSTM example

### ISSUE THREAD

**Issue by turambar** [tomthetrainer/class_labs#2]
- [x] Copy over the non-Spark LSTM example to the solutions folder in [physionet branch](https://github.com/tomthetrainer/class_labs/tree/physionet)
- [x] modify pom.xml file as needed
- [x] make sure everything builds and runs!
- [x] file a PR and request reviews from @davekale and @tomthetrainer

**Comment by bpark738** [comment]
Done
